# Copyright (C) 2026 Ronald Rink, d-fens GmbH, http://d-fens.ch
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published
# by the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.
#
# SPDX-License-Identifier: AGPL-3.0-or-later

"""``coverage-badge`` -- generate a static SVG coverage badge from .coverage data.

Reads the code coverage data file (.coverage) generated by ``coverage run``,
extracts the total percentage, and renders a flat-style SVG badge suitable for
embedding in README and other documentation. The badge color is determined by
coverage threshold: ≥90% green, ≥75% yellowgreen, ≥50% yellow, else red.

Run this after ``coverage run -m unittest discover`` and commit the result.
"""

from pathlib import Path
from typing import Annotated

import typer


def _get_coverage_percentage() -> float:
    """Read .coverage data and return the total percentage as a float (0-100).

    Raises SystemExit if .coverage file does not exist.
    """
    try:
        import coverage as coverage_module
    except ImportError as e:
        msg = "coverage package not found; install with: pip install coverage"
        raise SystemExit(msg) from e

    coverage_file = Path(".coverage")
    if not coverage_file.exists():
        msg = (
            "No .coverage file found. Run tests first with:\n"
            "  uv run --frozen coverage run -m unittest discover -v -s tests -t . -p 'test_*.py'\n"
        )
        raise SystemExit(msg)

    cov = coverage_module.Coverage()
    cov.load()

    # cov.report() returns the overall percentage (0-100).
    # We suppress output since we only want the number.
    total_percent = cov.report(skip_covered=False)
    if total_percent is None:
        msg = "Failed to compute coverage percentage from .coverage data"
        raise SystemExit(msg)

    return total_percent


def _color_for_coverage(percent: float) -> str:
    """Return a color name for the given coverage percentage.

    Thresholds match shields.io's coverage badge scale:
    - ≥90: green
    - ≥75: yellowgreen
    - ≥50: yellow
    - <50: red
    """
    if percent >= 90:
        return "green"
    if percent >= 75:
        return "yellowgreen"
    if percent >= 50:
        return "yellow"
    return "red"


def _render_svg_badge(coverage_percent: float) -> str:
    """Render a flat-style SVG coverage badge.

    Returns the full SVG string (XML), ready to write to a .svg file.
    Badge shows label "coverage" and value "NN%" with color based on percentage.
    """
    percent_str = f"{coverage_percent:.0f}%"
    color = _color_for_coverage(coverage_percent)

    # Flat-style badge: label on left (blue), value on right (color-based)
    # Approximate widths: "coverage" ~60px, "NN%" ~35px, plus margins
    label_width = 60
    value_width = 35
    label_x = label_width / 2
    value_x = label_width + value_width / 2
    total_width = label_width + value_width

    # SVG colors (shields.io standard palette)
    color_map = {
        "blue": "#4c1",
        "green": "#4c1",
        "yellowgreen": "#a3c51c",
        "yellow": "#dfb317",
        "red": "#e05d44",
    }
    value_color = color_map.get(color, "#e05d44")
    label_color = "#555"
    text_color = "#fff"

    # noqa: E501 - SVG generation produces long lines by necessity
    svg = (  # noqa: E501
        f'<svg xmlns="http://www.w3.org/2000/svg" '
        f'xmlns:xlink="http://www.w3.org/1999/xlink" '
        f'width="{total_width}" height="20" role="img" aria-label="coverage: {percent_str}">\n'
        f"  <title>coverage: {percent_str}</title>\n"
        f'  <linearGradient id="s" x2="0" y2="100%">\n'
        f'    <stop offset="0" stop-color="#bbb"/>\n'
        f'    <stop offset="1" stop-opacity=".1"/>\n'
        f"  </linearGradient>\n"
        f'  <clipPath id="r">\n'
        f'    <rect width="{total_width}" height="20" rx="3" fill="#fff"/>\n'
        f"  </clipPath>\n"
        f'  <g clip-path="url(#r)">\n'
        f'    <rect width="{label_width}" height="20" fill="{label_color}"/>\n'
        f'    <rect x="{label_width}" width="{value_width}" height="20" fill="{value_color}"/>\n'
        f'    <rect width="{total_width}" height="20" fill="url(#s)"/>\n'
        f"  </g>\n"
        f'  <g fill="{text_color}" text-anchor="middle" font-family="Verdana,Geneva,DejaVu Sans,sans-serif" text-rendering="geometricPrecision" font-size="110">\n'  # noqa: E501
        f'    <text aria-hidden="true" x="{label_x * 10}" y="150" fill="#010101" fill-opacity=".3" transform="scale(.1)" textLength="{(label_width - 10) * 10}">coverage</text>\n'  # noqa: E501
        f'    <text x="{label_x * 10}" y="140" transform="scale(.1)" fill="{text_color}" textLength="{(label_width - 10) * 10}">coverage</text>\n'  # noqa: E501
        f'    <text aria-hidden="true" x="{value_x * 10}" y="150" fill="#010101" fill-opacity=".3" transform="scale(.1)" textLength="{(value_width - 10) * 10}">{percent_str}</text>\n'  # noqa: E501
        f'    <text x="{value_x * 10}" y="140" transform="scale(.1)" fill="{text_color}" textLength="{(value_width - 10) * 10}">{percent_str}</text>\n'  # noqa: E501
        f"  </g>\n"
        f"</svg>"
    )
    return svg


def coverage_badge(
    output: Annotated[
        Path | None,
        typer.Option(
            "--output",
            "-o",
            help="Path to write coverage badge SVG into (default: docs/coverage.svg).",
        ),
    ] = None,
) -> None:
    """Generate coverage badge SVG from .coverage data.

    Reads the code coverage data file (.coverage), computes the overall
    percentage, and renders a flat-style SVG badge with color based on
    coverage threshold. Write to ``docs/coverage.svg`` by default, or to
    a custom path with ``--output``. Run this after ``coverage run -m unittest discover``
    and commit the result.
    """
    coverage_percent = _get_coverage_percentage()
    svg_content = _render_svg_badge(coverage_percent)

    output_path = output if output is not None else Path("docs/coverage.svg")
    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(svg_content, encoding="utf-8")
    typer.echo(f"✓ Wrote {output_path} ({coverage_percent:.0f}% coverage)")
