# Copyright (C) 2026 Ronald Rink, d-fens GmbH, http://d-fens.ch
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published
# by the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.
#
# SPDX-License-Identifier: AGPL-3.0-or-later

"""One item of a markdown bullet or numbered list, usable only via `list[MarkdownListItem]`."""

from __future__ import annotations

import re

from pydantic import computed_field

from .markdown_str import MarkdownStr
from ._markdown import format_text, md

#: The two markdown-it block-container token types a list item can be nested under.
#: `MarkdownListItem` is deliberately shared between bullet (`ul`) and ordered (`ol`)
#: lists rather than split into per-kind subclasses -- the marker style ("-", "1.")
#: is incidental, not structural, and is always regenerated by the final `mdformat`
#: normalization pass (see `_markdown.format_text`), never tracked by this class.
_LIST_OPEN_TYPES = ("bullet_list_open", "ordered_list_open")

#: Matches a bullet ("-", "*", "+") or ordered (e.g. "1.", "1)") list item marker plus
#: the single space `mdformat` always renders after it, at the start of a line.
_MARKER_RE = re.compile(r"^(?:[-*+]|\d+[.)]) ")


class MarkdownListItem(MarkdownStr):
    """One item ("li") of a markdown bullet or numbered list.

    Unlike `MarkdownSection`/`MarkdownParagraph`, there is no dedicated
    container class for the list itself (no `MarkdownList`/`MarkdownBulletList`/
    `MarkdownOrderedList`) -- a `MarkdownListItem` (or a subclass of it) is used
    purely as `items: list[MarkdownListItem]` (or `list[MarkdownListItem] | None`)
    on whatever `MarkdownSection`/`MarkdownParagraph`/`MarkdownListItem` wants a
    list-shaped field, fully reusing the existing `list[MarkdownStr]` machinery
    (`MarkdownStr.process_list_field`, already built for `Optional`/repeated
    fields in general). Consequently a bare `MarkdownListItem` can only ever be
    parsed as part of such a list -- `get_extent`/`from_text` both require the
    enclosing `bullet_list_open`/`ordered_list_open` wrapper token to be present,
    so it cannot be used as a top-level/scalar field type on its own.

    Every item is assumed to start with at least one paragraph (its own lead
    text) -- `from_text` asserts this.

    - Leaf (no nested `MarkdownStr`/`list[MarkdownStr]` fields declared, the
      default for a bare `MarkdownListItem`): `_value` holds the item's
      complete extent verbatim, marker and any nested content (e.g. an
      un-modelled nested sub-list) included -- nothing else will ever retain
      it, exactly like a leaf `MarkdownSection`/`MarkdownParagraph`.
    - Composite (a subclass declares fields, e.g. a nested
      `notes: list[MarkdownListItem]` for a sub-list): `_value` holds only the
      item's own leading paragraph, verbatim *including its marker*
      (`"- "`/`"1. "`) -- unlike `MarkdownParagraph`, whose marker-free prose
      needs no reconstruction, a list item's marker cannot be reconstructed
      from class metadata (it depends on bullet-vs-ordered and, for ordered
      lists, the item's final position, neither of which the item itself
      knows), so it is kept verbatim instead. The remainder is dedented and
      delegated to `super().from_text()` for the declared fields, exactly
      like `MarkdownParagraph`'s composite case; `__str__` re-indents the
      declared fields' rendered output by the marker's own width before
      recombining.

    Round-trip note: because every item is independently sliced,
    `mdformat`-renormalized, and (for a composite item) reassembled by this
    class before the *parent* class's already-existing `list[MarkdownStr]`
    rendering rejoins every item, a genuinely *tight* source list currently
    round-trips to a structurally-equivalent *loose* list rather than a
    byte-exact one -- an accepted, documented exception to the engine's
    otherwise byte-exact round-trip (loose lists are unaffected and remain
    byte-exact). This matches this feature's own founding ADR, which already
    treats list-rendering variance as out of scope for byte-exact fidelity.
    """

    @classmethod
    def get_extent(cls, text: str) -> int:
        """Return the extent of this list item, as a line count.

        There is only an extent at all if the *first* token parsed from
        `text` is a list-open wrapper (`bullet_list_open`/`ordered_list_open`)
        immediately followed by a `list_item_open` token -- i.e. `text`
        starts with (at least) one list item, whether `text` is a whole
        remaining multi-item list (only the *first* item's extent is
        reported) or an already-isolated single-item slice (the only shape
        `bullet_list_open`/`ordered_list_open` allow on their own, since
        CommonMark cannot represent a lone list item without its wrapper).
        Otherwise this returns `0`, same as the base class's "no extent" case.

        `list_item_open`'s own `.map` already spans the item's *entire*
        content, including any nested list -- unlike `heading_open`/
        `paragraph_open`, there is no separate stop-condition scan needed.

        Args:
            text: Markdown source, pre-formatted with `mdformat`.

        Returns:
            0: `text` does not start with a list item (no extent).
            int > 0: line count (see `MarkdownStr.get_extent`) covered by the
                first list item in `text`.
        """
        assert isinstance(text, str), type(text)
        assert text == format_text(text), "text is not in 'mdformat'."

        tokens = md.parse(text)

        if len(tokens) < 2 or tokens[0].type not in _LIST_OPEN_TYPES or tokens[1].type != "list_item_open":
            return 0

        own_map = tokens[1].map
        assert own_map and len(own_map) == 2, f"{cls.__name__}: list_item_open token has no line map"

        return own_map[1]

    @classmethod
    def from_text(cls, text: str) -> MarkdownListItem:
        """Create an instance from markdown text starting with a list item.

        Validates that `text` starts with a list-open wrapper
        (`bullet_list_open`/`ordered_list_open`) followed by a
        `list_item_open`/`paragraph_open` pair -- every item is assumed to
        start with at least one paragraph. There is no `@alias` check, same
        as `MarkdownParagraph` -- an item's text is free-form content, not a
        title.

        If `cls` declares no nested `MarkdownStr` fields (leaf case), nothing
        else will ever retain this item's text, so `_value` is set to the
        complete extent `from_text` received (marker and any nested content
        included, verbatim).

        Otherwise the item's own leading paragraph's line span is stripped
        off `text`, the remainder is dedented (`mdformat` dedents an
        indented sub-block automatically once it is renormalized on its own)
        and delegated to `MarkdownStr.from_text` (via `super()`) for the
        declared fields' population. `_value` is set to the leading
        paragraph's own lines verbatim, *marker included* -- unlike
        `MarkdownParagraph`, whose marker-free `_value` needs no
        reconstruction, an item cannot reconstruct its own marker from class
        metadata alone (see the class docstring), so it is kept as-is instead.
        """
        assert isinstance(text, str), f"text: '{type(text)}' != 'str'."
        assert text == format_text(text), "text is not in 'mdformat'."

        tokens = md.parse(text)
        assert len(tokens) >= 5, "Expected at least a list-open/list_item_open/paragraph triple"

        t_list_open = tokens[0]
        t_item_open = tokens[1]
        t_para_open = tokens[2]
        t_para_close = tokens[4]

        assert t_list_open.type in _LIST_OPEN_TYPES, (
            f"{cls.__name__}: expected a list wrapper, got '{t_list_open.type}'."
        )
        assert t_item_open.type == "list_item_open" and t_item_open.tag == "li", (
            f"{cls.__name__}: expected 'list_item_open'/'li', got '{t_item_open.type}'/'{t_item_open.tag}'."
        )
        assert t_para_open.type == "paragraph_open", (
            f"{cls.__name__}: expected every list item to start with a paragraph, got '{t_para_open.type}'."
        )
        assert t_para_close.nesting == -1, (
            f"Token[4]: expected a closing tag, got '{t_para_close.type}' '{t_para_close.nesting}'."
        )

        field_names = cls._get_field_names()

        if not field_names:
            instance = cls()
            instance._value = text
            return instance

        own_map = t_para_open.map
        assert own_map and len(own_map) == 2, f"{cls.__name__}: paragraph_open token has no line map"
        own_lines = own_map[1]

        lines = text.splitlines()
        body_lines = lines[own_lines:]
        body_text = format_text("\n".join(body_lines)) if body_lines else ""

        instance = super().from_text(body_text)
        instance._value = "\n".join(lines[:own_lines])
        return instance

    def __str__(self) -> str:
        """Return markdown representation, including this item's own marker.

        Leaf case (no declared nested fields): `_value` already holds the
        complete extent verbatim (marker included, see `from_text`), so this
        defers to `super().__str__()` (`MarkdownStr.__str__`'s leaf branch,
        which returns `_value` unchanged).

        Composite case: re-indents `super().__str__()`'s children output (the
        declared fields' own rendering, dedented since `from_text`) by this
        item's own marker width, derived from `_value`'s first line, then
        recombines it with `_value` -- mirroring `MarkdownSection.__str__`'s
        composite reconstruction, just with a marker-width indent instead of
        a heading prefix.
        """
        if not self._get_field_names():
            return super().__str__()

        first_line = self._value.splitlines()[0] if self._value else ""
        match = _MARKER_RE.match(first_line)
        assert match, f"{type(self).__name__}: expected a list item marker at the start of {first_line!r}"
        indent_width = match.end()

        body = super().__str__()
        reindented = "\n".join((" " * indent_width + line) if line else "" for line in body.splitlines())

        return format_text(f"{self._value}\n\n{reindented}\n")

    @computed_field  # type: ignore
    @property
    def text(self) -> str:
        """Computed property that extracts this item's leading paragraph text.

        Re-parses `_value` (which, whether leaf or composite, always starts
        with this item's own leading paragraph, see `from_text`) and returns
        the first paragraph's inline text, with the item's marker and any
        indentation stripped -- mirroring `MarkdownSection.name`'s pattern of
        deriving a plain-text convenience view from the stored markdown.

        Returns:
            The leading paragraph's text without markdown list markup, or an
            empty string if `_value` is unset (e.g. before `from_text` runs).

        Example:
            >>> item = MarkdownListItem.from_text("- We know Buyer\\n")
            >>> item.text
            'We know Buyer'
        """
        tokens = md.parse(self._value)

        for i, token in enumerate(tokens):
            if token.type == "inline" and i > 0 and tokens[i - 1].type == "paragraph_open":
                return token.content.strip()

        return ""
