# Copyright (C) 2026 Ronald Rink, d-fens GmbH, http://d-fens.ch
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published
# by the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.
#
# SPDX-License-Identifier: AGPL-3.0-or-later

"""Resource: specmgr://req/schema (Task 3.5).

Reads the already-persisted ``docs/req_schema.json`` directly from disk --
trusts the ``specmgr-schema`` pre-commit hook (and its CI step) to keep it
current, the same trust model ``adr-toc``'s ``docs/adr/README.md`` already
relies on. Deliberately does not import
``commands.schema.generate_req_schema()`` (which would leak the ``cli``
extra's ``typer`` dependency into the ``mcp`` extra's import graph), nor
regenerate the file on the fly -- this is a plain, read-only disk read.

The resource's URI is deliberately unversioned (no ``/v1``) even though the
file it reads is a ``req/models/v1``-derived artifact -- see
`.specmgr/feat/feat-6-requirement-artifact/README.md`'s Decisions Made.
"""

from __future__ import annotations

import json
from typing import Any

from ..._paths import DOCS_DIR
from ...server import mcp

#: Fixed on-disk location of the generated REQ JSON Schema. Not
#: configurable (no env var) -- this is a build-time artifact of *this*
#: package's own source tree, not user-authored content elsewhere on disk
#: (contrast with ``adr.tools._paths.adr_base_dir``'s ``SPECMGR_ADR_DIR``).
_REQ_SCHEMA_PATH = DOCS_DIR / "req_schema.json"


@mcp.resource(
    "specmgr://req/schema",
    name="req_schema",
    title="REQ JSON Schema",
    description=(
        "The persisted REQ JSON Schema (2020-12 dialect, docs/req_schema.json), generated by "
        "`specmgr schema` and kept current by a pre-commit hook/CI step. Includes a `$comment` "
        "schema-layout version marker for detecting a shape change without diffing the whole "
        "document."
    ),
    mime_type="application/json",
)
def req_schema() -> dict[str, Any]:
    """Return the parsed contents of ``docs/req_schema.json``.

    Reads the file fresh on every call (no in-memory cache, consistent with
    every other resource/tool in this codebase) but never regenerates it --
    schema presence is guaranteed at build time by the ``specmgr-schema``
    pre-commit hook and CI step, so a missing or corrupted file is treated
    as a hard failure rather than defensively handled.

    Returns
    -------
    dict[str, Any]
        The parsed JSON Schema document (top-level keys include
        ``$schema``, ``$comment``, ``$defs``, ``properties``, ...).

    Raises
    ------
    FileNotFoundError
        If ``docs/req_schema.json`` does not exist.
    json.JSONDecodeError
        If the on-disk file is not valid JSON.
    """
    result: dict[str, Any] = json.loads(_REQ_SCHEMA_PATH.read_text(encoding="utf-8"))
    return result
